//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityBuildings.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuildingsDBEntities : DbContext
    {
        public BuildingsDBEntities()
            : base("name=BuildingsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Attachments> Attachments { get; set; }
        public virtual DbSet<Faculty_Buildings> Faculty_Buildings { get; set; }
        public virtual DbSet<Hospital_Buildings> Hospital_Buildings { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Other_Buildings> Other_Buildings { get; set; }
    }
}
