//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityBuildings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty_Buildings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faculty_Buildings()
        {
            this.Attachments = new HashSet<Attachments>();
            this.Images = new HashSet<Images>();
        }
    
        public int ID { get; set; }
        public string Faculty_Name { get; set; }
        public string Faculty_NameEN { get; set; }
        public string Faculty_Dean { get; set; }
        public string Faculty_DeanEN { get; set; }
        public Nullable<short> Faculty_Buildings_Number { get; set; }
        public string Faculty_Genesis { get; set; }
        public string Faculty_Vision { get; set; }
        public string Faculty_VisionEN { get; set; }
        public string Faculty_Message { get; set; }
        public string Faculty_MessageEN { get; set; }
        public string Faculty_Details { get; set; }
        public string Faculty_DetailsEN { get; set; }
        public string Faculty_Link { get; set; }
        public Nullable<short> Faculty_Main_Building_Floors { get; set; }
        public Nullable<short> Faculty_Main_Building_Stages { get; set; }
        public Nullable<short> Faculty_Main_Building_Labs { get; set; }
        public string Faculty_Restaurant_Place { get; set; }
        public string Faculty_Restaurant_PlaceEN { get; set; }
        public string Faculty_Link_FaceBook { get; set; }
        public string Faculty_Link_Twitter { get; set; }
        public string Faculty_Link_YouTube { get; set; }
        public string Faculty_Phone_Number { get; set; }
        public string Faculty_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachments> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
    }
}
