//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityBuildings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital_Buildings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hospital_Buildings()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int ID { get; set; }
        public string Hospital_Name { get; set; }
        public string Hospital_NameEN { get; set; }
        public string Hospital_Genesis { get; set; }
        public Nullable<short> Hospital_Floors { get; set; }
        public string Hospital_Manager_Name { get; set; }
        public string Hospital_Manager_NameEN { get; set; }
        public string Hospital_Sections { get; set; }
        public string Hospital_SectionsEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
    }
}
