//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityBuildings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Other_Buildings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Other_Buildings()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int ID { get; set; }
        public string Building_Name { get; set; }
        public string Building_NameEN { get; set; }
        public string Building_Units { get; set; }
        public string Building_UnitsEN { get; set; }
        public string Building_Services { get; set; }
        public string Building_ServicesEN { get; set; }
        public string Building_Responsible_Name { get; set; }
        public string Building_Responsible_NameEN { get; set; }
        public string Building_Genesis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
    }
}
