//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityBuildings.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversityBuildings.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمهورية مصر العربية - محافظة المنيا - جامعة المنيا.
        /// </summary>
        public static string addressPlace {
            get {
                return ResourceManager.GetString("addressPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منشآت جامعية.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مباني ومنشآت جامعية.
        /// </summary>
        public static string carousel {
            get {
                return ResourceManager.GetString("carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مباني ومنشآت جامعية. كل ما تريد معرفته عن المباني الجامعية الخاصة بـ. المبنى بتفاصيله من أدوار ووحدات وخدمات وأشياء أخرى.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقدم للمستخدمين كافه الصور التي تشمل جميع مباني ومنشئات جامعيه وعرض تلك الصوربطريقه واضحه ومنسقه والتي توجد داخل الحرم الجامعي وخارجه.
        /// </summary>
        public static string DolorSitema {
            get {
                return ResourceManager.GetString("DolorSitema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكليات.
        /// </summary>
        public static string FacultyBuildings {
            get {
                return ResourceManager.GetString("FacultyBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرفة المزيد عن المستشفى.
        /// </summary>
        public static string HospitalLearnMore {
            get {
                return ResourceManager.GetString("HospitalLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستشفيات.
        /// </summary>
        public static string hospitals {
            get {
                return ResourceManager.GetString("hospitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعض صور من المستشفيات.
        /// </summary>
        public static string hosSearchPhoto {
            get {
                return ResourceManager.GetString("hosSearchPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مباني ومنشآت جامعية, المباني الجامعية, الكليات.
        /// </summary>
        public static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرفة المزيد عن الكلية.
        /// </summary>
        public static string learnMore {
            get {
                return ResourceManager.GetString("learnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقدم للمستخدمين  شرح وافي لجميع المباني كعدد المباني والادواروالاقسام بالكليات وتاريخ البناء ومعلومات كثيره هامه اخري.
        /// </summary>
        public static string LoremIpsum {
            get {
                return ResourceManager.GetString("LoremIpsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقدم خريطه للجامعه كامله لتسهل علي المستخدمين وتوضح لهم جميع المباني والاتجاهات والطريق حتي تسهل لهم التحرك داخل الجامعه بطريقه سهله.
        /// </summary>
        public static string MagniDolores {
            get {
                return ResourceManager.GetString("MagniDolores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المباني الأخرى.
        /// </summary>
        public static string otherBuildings {
            get {
                return ResourceManager.GetString("otherBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعض صور من المباني الأخرى.
        /// </summary>
        public static string otherSearchPhoto {
            get {
                return ResourceManager.GetString("otherSearchPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرفة المزيد عن المباني الأخرى.
        /// </summary>
        public static string OthersLearnMore {
            get {
                return ResourceManager.GetString("OthersLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مباني ومنشآت جامعية - جميع الحقوق محفوظة لجامعة المنيا.
        /// </summary>
        public static string rights {
            get {
                return ResourceManager.GetString("rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث في.
        /// </summary>
        public static string searchFor {
            get {
                return ResourceManager.GetString("searchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعض صور من الكليات.
        /// </summary>
        public static string searchPhoto {
            get {
                return ResourceManager.GetString("searchPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     بحث....
        /// </summary>
        public static string searchPlace {
            get {
                return ResourceManager.GetString("searchPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الصورة.
        /// </summary>
        public static string showPhoto {
            get {
                return ResourceManager.GetString("showPhoto", resourceCulture);
            }
        }
    }
}
